/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ui;

import battleships.Status;

import java.io.IOException;
import java.util.LinkedList;

public class App {

    public static final String WELCOME = "Welcome to battleships (light)";
    public static final String ENTER_NAME = "Enter your name: ";
    public static final String SELECT_AN_OPTION = "Select an option: ";
    public static final String INVALID_OPTION = "Select a valid option between 0 and ";


    public static void main(String[] args) throws IOException {

        System.out.println(WELCOME);


        BattleshipsUI userInterface = new BattleshipsUI(Console.readString(ENTER_NAME));

        LinkedList<Command> networkList = userInterface.returnNetworkList();
        LinkedList<Command> setList = userInterface.returnSetList();
        LinkedList<Command> attackList = userInterface.returnAttackList();
        System.out.println(buildCommandMenu(networkList));
        System.out.println(selectCommand(networkList).execute());
        boolean connected = false;

        do {
            if (userInterface.gameStarted()) {
                connected = true;
            }
        } while (!connected);
        userInterface.printOwnBoard();

        do {
            System.out.println(buildCommandMenu(setList));
            System.out.println(selectCommand(setList).execute());
        } while (userInterface.getStatus() == Status.SET);
        userInterface.printEnemyBoard();
        do {
            System.out.println(buildCommandMenu(attackList));
            System.out.println(selectCommand(attackList).execute());
        } while (true);

    }

    private static String buildCommandMenu(LinkedList<Command> commands) {

        StringBuilder builder = new StringBuilder();
        builder.append(System.lineSeparator());
        builder.append(System.lineSeparator()).append(SELECT_AN_OPTION).append(System.lineSeparator());
        builder.append(System.lineSeparator());
        for (int i = 1; i < commands.size(); i++) {
            Command cmd = commands.get(i);
            builder.append(" ").append(i).append(". ").append(cmd.description()).append(System.lineSeparator());
        }
        builder.append(" " + 0 + ". ").append(commands.get(0).description()).append(System.lineSeparator());
        return builder.toString();
    }

    static private Command selectCommand(LinkedList<Command> commands) {

        do {
            int select = Console.readInteger(SELECT_AN_OPTION);
            if (select >= 0 && select < commands.size()) {
                return commands.get(select);
            }
            System.out.println(INVALID_OPTION + (commands.size() - 1));
        }
        while (true);
    }
}
